---
- name: 'Baixa o arquivo de instalacao do Wordpress'
  get_url:
    url: https://wordpress.org/latest.tar.gz'
    dest: '/tmp/wordpress.tar.gz'
    mode: 0440

- name: 'Descompacta o wordpress'
  unarchive:
    src: '/tmp/wordpress.tar.gz'
    dest: '/var/www/'
    remote_src: yes
  become: yes
  vars:
    ansible_become_pass: "{{ become_pass }}"

- copy:
    src: "{{ wp_wordpress_folder }}/wp-config-sample.php"
    dest: "{{ wp_wordpress_folder }}/wp-config.php"
    remote_src: yes
  become: yes
  vars:
    ansible_become_pass: "{{ become_pass }}"

- name: Remove file (delete file)
  ansible.builtin.file:
    path: /tmp/wordpress.tar.gz
    state: absent
    
- name: 'Configura o wp-config com as entradas do banco de dados'
  replace:
    path: "{{ wp_wordpress_folder }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
    backup: yes
  with_items:
    - { regex: 'database_name_here', value: "{{ wp_db_name }}"}
    - { regex: 'username_here', value: "{{ wp_user }}"}
    - { regex: 'password_here', value: "{{ wp_pass }}"}
    - { regex: 'localhost', value: "{{ wp_ip }}"}
  become: yes
  vars:
    ansible_become_pass: "{{ become_pass }}"    

- name: 'Configura Apache para servir o WOrdpress'
  template:
    src: 'templates/000-default.conf.j2'
    dest: '/etc/apache2/sites-available/000-default.conf'
  notify:
    - restart apache
  become: yes
  vars:
    ansible_become_pass: "{{ become_pass }}"